const b = 10;
const c = 20;
let Plus = c + b;
let Minus = b - c;
let Multiply = b * c;
let Divide = b / c;
    console.log("Plus:", Plus);
    console.log("Minus", Minus);
    console.log("Multiply", Multiply);
    console.log("Divide:", Divide);
